version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - backend
    container_name: php  
    volumes:
      - ./cakephp-4-0-3/:/var/www/html/
    links:
      - mysql
  apache:
    build: './apache/'
    container_name: apache
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    links:
      - mysql
    ports:
      - "1236:80"
    volumes:
      - ./cakephp-4-0-3/:/var/www/html/
  mysql:
    image: mysql
    container_name: mysql
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
       - ./mysql/:/var/lib/mysql
  pma:
    build: './pma/'
    container_name: pma
    networks:
       - backend
    ports:
       - "1237:80"
    links: 
      - mysql:mysql
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
      - PMA_PORT=3306
networks:
  frontend:
  backend: